name: CD Pipeline - Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
