name: CD Pipeline - Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          echo "Deployment triggered on Render Production Environment."
